language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
script:
  - sbt test
  - sbt "project coreJVM" "clean" "coverage" "test"
  - sbt "project binaryJVM" "clean" "coverage" "test"
  - sbt coverageAggregate
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
  - sbt coveralls
scala:
   - 2.11.7
jdk:
   - oraclejdk7